name: Publish to crates.io

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: 🚀 Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test
        run: |
          cd recovery
          cargo clippy -- -D warnings
          cargo test --release

      - name: 🚀 Publish crate (recovery-derive)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd recovery-derive
          cargo publish

      - name: 🚀 Publish crate (recovery)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd recovery
          cargo publish
