name: Publish to crates.io

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: 🚀 Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🧪 Test
        run: |
          cd recovery
          cargo clippy -- -D warnings
          cargo test --release

      - name: 🚀 Publish crate (recovery-derive)
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: recovery-derive

      - name: 🚀 Publish crate (recovery)
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: recovery
